# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govaultenv < Formula
  desc ""
  homepage ""
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.2.2/govaultenv_1.2.2_darwin_amd64.tar.gz"
      sha256 "bc678eb25f75f138a65c50966e91741cf799592bf1598b5a6a1f6153d23448d4"

      def install
        bin.install "govaultenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.2.2/govaultenv_1.2.2_darwin_arm64.tar.gz"
      sha256 "6f39dc5174a5657425bbb3e0100db1bda109a77dcdbeacd8a50463db09777410"

      def install
        bin.install "govaultenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.2.2/govaultenv_1.2.2_linux_amd64.tar.gz"
      sha256 "91f1cc7cb109a48c90ad369520178af7d7f84935521f120f4ab2d21802afed7a"

      def install
        bin.install "govaultenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.2.2/govaultenv_1.2.2_linux_arm64.tar.gz"
      sha256 "4ac2fab2347eed7b227d8b6734cc3f778537f9058d5f8602bf94eb4be82c1610"

      def install
        bin.install "govaultenv"
      end
    end
  end
end
