# This file was generated by GoReleaser. DO NOT EDIT.
class Govaultenv < Formula
  desc ""
  homepage ""
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jamhed/govaultenv/releases/download/v1.1.0/govaultenv_1.1.0_darwin_amd64.tar.gz"
    sha256 "5c17368b3fd6ea9a21f52516ad8718e84fbdbe0b7538c4ff2f623a38ab87f6e1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.1.0/govaultenv_1.1.0_linux_amd64.tar.gz"
      sha256 "41062d5d906e00d03e8ca292ff7ecb4a6d8426001391d2cab55c5c1137775b7a"
    end
  end

  def install
    bin.install "govaultenv"
  end
end
