# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govaultenv < Formula
  desc ""
  homepage ""
  version "1.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.1.7/govaultenv_1.1.7_darwin_arm64.tar.gz"
      sha256 "d3af6e03ca92ab3fc75539064fd598c0b6ab86c0893780b079fbd3447ec03054"

      def install
        bin.install "govaultenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.1.7/govaultenv_1.1.7_darwin_amd64.tar.gz"
      sha256 "816dd4a64ab3f5517c52f02ed714b132b724fc4dcfa259a5ad0f048465c26ce8"

      def install
        bin.install "govaultenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.1.7/govaultenv_1.1.7_linux_amd64.tar.gz"
      sha256 "ce79339896e830bd04de420c6d01e52aa0596dc7bea5b40859aea68efc4a4977"

      def install
        bin.install "govaultenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamhed/govaultenv/releases/download/v1.1.7/govaultenv_1.1.7_linux_arm64.tar.gz"
      sha256 "f2921afbb049b51b0dab188682ec30d0c5c27ec8f373f17cd79b492fd50eca3b"

      def install
        bin.install "govaultenv"
      end
    end
  end
end
